Match (n) Set n.hetionet='yes', n.resource=['Hetionet'];
Match ()-[n]->() Set n.hetionet='yes', n.resource=['Hetionet'];
Match ()-[n]->() Where n.pubMedIDs is not NULL Set n.pubMed_ids=n.pubMedIDs Remove n.pubMedIDs;
Match ()-[n]->() Where n.pubmed_ids is not NULL Set n.pubMed_ids=n.pubmed_ids Remove n.pubmed_ids;
MATCH (n:Anatomy) where n.bto_id  is not NULL or n.mesh_id is not NULL Set n.xrefs=[];
MATCH (n:Anatomy) where n.bto_id is not NULL Set n.xrefs=n.xrefs + ["BTO:"+n.bto_id];
MATCH (n:Anatomy) where n.mesh_id is not NULL Set n.xrefs=n.xrefs + ["MeSH:"+n.mesh_id];
Match (g:Gene) Set g.identifier=toString(g.identifier);
MATCH (n:Symptom) Set n.xrefs=["MESH:"+n.identifier];
Match ()-[r]->() Where r.sources is not NULL Set r.source=apoc.text.join(r.sources, ',') Remove r.sources;
Match (:Compound)-[r]->(:Compound) Where r.similarity is not NULL Set r.similarity_dice_and_ecfp=r.similarity Remove r.similarity;
Match (a:Compound)-[r:CAUSES_CcSE]->(b:SideEffect) Delete r;
Match (n:SideEffect) Delete n;
Match (a:Compound)-[r:BINDS_CbG]->(b) Create (a)-[h:BINDS_CHbG]->(b) Set h=r Delete r;
Match (a:Compound)-[r:DOWNREGULATES_CdG]->(b) Create (a)-[h:DOWNREGULATES_CHdG]->(b) Set h=r Delete r;
Match (a:Compound)-[r:UPREGULATES_CuG]->(b) Create (a)-[h:UPREGULATES_CHuG]->(b) Set h=r Delete r;
Match (a:Compound)-[r:TREATS_CtD]->(b) Create (a)-[h:TREATS_CHtD]->(b) Set h=r Delete r;
Match (a:Compound)-[r:PALLIATES_CpD]->(b) Create (a)-[h:PALLIATES_CHpD]->(b) Set h=r Delete r;
Match ()-[n]->() Where n.source='Bgee' Set n.license='CC0 1.0';
Match ()-[n]->() Where n.source='Bgee,TISSUES' Set n.license='CC BY 4.0 Deed';
Match ()-[n]->() Where n.source='DOAF' Set n.license='CC BY 4.0 Deed';
Match ()-[n]->() Where n.source='ERC' Set n.license='CC0 1.0';
Match ()-[n]->() Where n.source='LINCS L1000' Set n.license='CC BY 4.0';
